### ISSUE TITLE
Add cypress/recommended config failed with eslint 4.X

### ISSUE THREAD

**Issue by ignoreswing** [cypress-io/eslint-plugin-cypress#11]
```
{
    extends: [
        'plugin:cypress/recommended'
    ]
}
```
is the new feature after [Release 2.1.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v2.1.0)
and the dependency said it requires ``` peerDependencies: { eslint: '>= 3.2.1' }```

When I use eslint 5.9.0 and add this config, everything is fine. 
However, when I use eslint 4.6.1, it throw

**Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined**

	at messages.map.message (/Users/Sean/Desktop/ocr/frontend-src/node_modules/eslint/lib/formatters/stylish.js:68:36)
	at Array.map (native)
	at results.forEach.result (/Users/Sean/Desktop/ocr/frontend-src/node_modules/eslint/lib/formatters/stylish.js:53:22)
	at Array.forEach (native)
	at module.exports (/Users/Sean/Desktop/ocr/frontend-src/node_modules/eslint/lib/formatters/stylish.js:38:13)
	at printResults (/Users/Sean/Desktop/ocr/frontend-src/node_modules/eslint/lib/cli.js:90:20)
	at Object.execute (/Users/Sean/Desktop/ocr/frontend-src/node_modules/eslint/lib/cli.js:193:17)
	at Object.<anonymous> (/Users/Sean/Desktop/ocr/frontend-src/node_modules/eslint/bin/eslint.js:74:28)
	at Module._compile (module.js:570:32)
	at Object.Module._extensions..js (module.js:579:10)

It only works if I remove the config `plugin:cypress/recommended`

**Comment by chrisbreiding** [comment]
Thanks for bringing this to our attention. I hesitate to bump up the peer dependency requirement, since features other than the rules can work with older versions of eslint. 

To address that, I [added a caveat to the readme](https://github.com/cypress-io/eslint-plugin-cypress#rules) concerning the eslint 5 requirement for rules. I also [created an issue](https://github.com/cypress-io/eslint-plugin-cypress/issues/14) 
to track support for eslint 4.
