### ISSUE TITLE
no-unnecessary-waiting: TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by tomtomsen** [cypress-io/eslint-plugin-cypress#36]
using: `eslint-plugin-cypress@2.8.0`

I have a wrapper for `cy.wait`
Since 2.8.0 it results in an `Cannot read property 'value' of undefined` error
```js
const waitForImportToComplete = (timeout = 5000): void => {
    // eslint-disable-next-line cypress/no-unnecessary-waiting
    cy.wait(timeout);
};
```
The code above will produce the following error message
```shell
TypeError: Cannot read property 'value' of undefined
Occurred while linting /home/tomtomsen/development/myproject/src/index.ts:10
    at isIdentifierNumberConstArgument (/home/tomtomsen/development/myproject/node_modules/eslint-plugin-cypress/lib/rules/no-unnecessary-waiting.js:61:64)
    at CallExpression (/home/tomtomsen/development/myproject/node_modules/eslint-plugin-cypress/lib/rules/no-unnecessary-waiting.js:29:41)
    at listeners.(anonymous function).forEach.listener (/home/tomtomsen/development/myproject/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/tomtomsen/development/myproject/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/tomtomsen/development/myproject/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/home/tomtomsen/development/myproject/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/home/tomtomsen/development/myproject/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/home/tomtomsen/development/myproject/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
    at nodeQueue.forEach.traversalInfo (/home/tomtomsen/development/myproject/node_modules/eslint/lib/linter/linter.js:936:32)
```

https://github.com/cypress-io/eslint-plugin-cypress/blob/e66bdfd7e18bf273f85ef000d30a80b16d5467c2/lib/rules/no-unnecessary-waiting.js#L56
It seems that `resolvedIdentifier.defs[0]` is expected to be from type `Variable` but got `ParameterDefinition`, which does not have a `node.init.value` property.
I was not able to find a way to retrieve the default value of a parameter, otherwise i would have proposed a pull request.

**Comment by chrisbreiding** [comment]
Thanks for reporting. Fixed in [2.8.1](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v2.8.1).
