### ISSUE TITLE
Using exported constant in `cy.wait()` throws "TypeError: Cannot read property 'undefined' of undefined"

### ISSUE THREAD

**Issue by Zaxcoding** [cypress-io/eslint-plugin-cypress#78]
# Steps to reproduce

* In a typescript file, define a `const` number
* In a second typescript file, import that `const`
* Use the imported `const` in a `cy.wait()` call

# Expected behavior

* See "no-unnecessary-waiting" ESLint violation

# Actual behavior

* See "TypeError: Cannot read property 'undefined' of undefined", which can't be ignored by ESLint

# Stacktrace: 

> TypeError: Cannot read property 'undefined' of undefined
> Occurred while linting filename.ts:15
>     at isIdentifierNumberConstArgument (/node_modules/eslint-plugin-cypress/lib/rules/no-unnecessary-waiting.js:72:39)
>     at CallExpression (/node_modules/eslint-plugin-cypress/lib/rules/no-unnecessary-waiting.js:22:15)
>     at /node_modules/eslint/lib/linter/safe-emitter.js:45:58

#  Relevant line

https://github.com/cypress-io/eslint-plugin-cypress/blob/9bcf51e333b14750df3e0148995df172fd17ed60/lib/rules/no-unnecessary-waiting.js#L72

**Comment by luanraithz** [comment]
We are having the same issue, any workaround besides turning off this rule?

**Comment by CallumHoward** [comment]
Same issue here too

**Comment by CallumHoward** [comment]
Linking related PR here: https://github.com/cypress-io/eslint-plugin-cypress/pull/90
